name = "heranetwork-stats"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-22"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

routes = [
  { pattern = "estadisticas.heramc.net", custom_domain = true }
]